[build]
publish = "_site"
command = "npm run build"

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  cache-control = """
    max-age=0,
    no-cache,
    no-store,
    must-revalidate"""

[[redirects]]
from = "/:slug"
to = "/.netlify/functions/possum"
status = 200
force = true
_generated_by_eleventy_serverless = "possum"
